version: "3.9"

services:
  eureka:
    build: ./eureka-server
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/src/main/resources/keys:/app/keys
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - JWT_PUBLIC_KEY_PATH=/app/keys/public.pem
    networks:
      - microservices-net

  account-service:
    build: ./account-service
    container_name: account-service
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    volumes:
      - ./account-service/src/main/resources/keys:/app/keys
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - JWT_PRIVATE_KEY_PATH=/app/keys/private.pem
      - JWT_TTL_SECONDS=3600
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-net

  sales-service:
    build: ./sales-service
    container_name: sales-service
    depends_on:
      - eureka
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
