server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ---- Account Service ----
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/account/**
          filters:
            - RewritePath=/api/account/(?<path>.*), /${path}

        # ---- Product Service ----
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<path>.*), /${path}

        # ---- Sales Service ----
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
          filters:
            - RewritePath=/api/sales/(?<path>.*), /${path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
