server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

jwt:
#  public-key-path: classpath:keys/public.pem
  public-key-path: ${JWT_PUBLIC_KEY_PATH:file:/app/keys/public.pem}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.microservice.gateway: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html   # URL principal para acessar a UI central
    display-request-duration: true
    urls:
      - name: account-service
        url: /api/accounts/v3/api-docs
      - name: product-service
        url: /api/products/v3/api-docs
      - name: sales-service
        url: /api/sales/v3/api-docs